#!/usr/bin/env ruby

Encoding.default_external = Encoding::UTF_8 if defined? Encoding

require 'bundler/setup' if File.exist? File.expand_path('../../Gemfile', __FILE__)
require 'farmsim/cli'

FarmSim::CLI.run(ARGV)
